'use server';

/**
 * @fileOverview Adapts the system's communication style based on user intent.
 *
 * - adaptResponseTone - A function that adjusts the response tone based on user intent.
 * - AdaptResponseToneInput - The input type for the adaptResponseTone function.
 * - AdaptResponseToneOutput - The return type for the adaptResponseTone function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AdaptResponseToneInputSchema = z.object({
  userIntent: z.string().describe('The identified intent of the user.'),
  responseText: z.string().describe('The initial response text generated by the system.'),
});
export type AdaptResponseToneInput = z.infer<typeof AdaptResponseToneInputSchema>;

const AdaptResponseToneOutputSchema = z.object({
  adaptedResponse: z.string().describe('The response text adapted to the user intent.'),
});
export type AdaptResponseToneOutput = z.infer<typeof AdaptResponseToneOutputSchema>;

export async function adaptResponseTone(input: AdaptResponseToneInput): Promise<AdaptResponseToneOutput> {
  return adaptResponseToneFlow(input);
}

const prompt = ai.definePrompt({
  name: 'adaptResponseTonePrompt',
  input: {schema: AdaptResponseToneInputSchema},
  output: {schema: AdaptResponseToneOutputSchema},
  prompt: `You are HOPE, an AI assistant that adapts its communication style based on user intent.

  User Intent: {{{userIntent}}}
  Initial Response: {{{responseText}}}

  Based on the user intent, adapt the response to be more appropriate.  Consider the following:

  - Technical: precise, structured
  - Casual: friendly, concise
  - Emotional: calm, grounded, supportive

  Return the adapted response.
  `,
});

const adaptResponseToneFlow = ai.defineFlow(
  {
    name: 'adaptResponseToneFlow',
    inputSchema: AdaptResponseToneInputSchema,
    outputSchema: AdaptResponseToneOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
